# Generated by Django 4.2.8 on 2025-08-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeproject",
            name="protocol_url",
            field=models.URLField(
                blank=True, help_text="Link to study protocol (PROSPERO, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="gradeproject",
            name="supplementary_file",
            field=models.FileField(blank=True, null=True, upload_to="supplementary/"),
        ),
    ]
